In [1]:
from sklearn.naive_bayes import GaussianNB
import pickle
import pandas

In [2]:
file = "../data/dataset.csv"
data = pandas.read_csv(file)
data.head()

,G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,...,G24,G25,G26,G27,G28,G29,G30,G31,G32,Class
0,1,1,0,1,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,P1
1,0,0,0,0,0,1,0,1,1,1,...,0,0,0,0,0,1,0,0,1,P2
2,0,0,0,0,1,1,1,1,0,1,...,0,0,0,0,0,1,0,0,1,P3
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,P4
4,0,1,1,1,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,1,P5

In [3]:
x = data[data.columns[:-1].tolist()]
x

,G1,G2,G3,G4,G5,G6,G7,G8,G9,G10,...,G23,G24,G25,G26,G27,G28,G29,G30,G31,G32
0,1,1,0,1,1,1,1,0,0,0,...,1,0,0,0,0,0,1,0,0,1
1,0,0,0,0,0,1,0,1,1,1,...,0,0,0,0,0,0,1,0,0,1
2,0,0,0,0,1,1,1,1,0,1,...,1,0,0,0,0,0,1,0,0,1
3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,1,1,1,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
5,0,0,1,1,1,1,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
6,0,0,1,0,0,0,1,1,0,1,...,0,0,0,0,0,1,1,1,1,1
7,0,0,1,0,1,0,0,1,0,1,...,0,0,1,1,1,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
y = data["Class"]
y

0    P1
1    P2
2    P3
3    P4
4    P5
5    P6
6    P7
7    P8
8    P9
Name: Class, dtype: object

In [5]:
model = GaussianNB()
model.fit(x, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [6]:
confidence = model.score(x, y)
confidence

1.0

In [7]:
with open('model.pkl','wb') as m:
    pickle.dump(model,m)

In [8]:
file = "../data/disease.csv"
labels = pandas.read_csv(file)
labels.head()

,DiseaseId,DiseaseName,DiseaseCause,DiseaseSolution,DiseaseImage
0,P1,Scabies,Penularan karena terkena kucing lain;Tungau ya...,Pisahkan dengan kucing lain;Mandikan kucingmu;...,https://i0.wp.com/meongku.com/wp-content/uploa...
1,P2,Gastritis,Makan Berlebihan;Kucing makan sampah yang bera...,Melakukan pergantian pakan secara perlahan den...,https://www.wikihow.com/images_en/thumb/c/c9/R...
2,P3,Helminthiasis,Kucing memakan makanan kotor;Kutu yang berada ...,Menjaga kebersihan kucing;Memberikan obat caci...,https://3.bp.blogspot.com/-V7A0NxNKUvE/XFVBu23...
3,P4,Rhintis,Ditularkan dari kucing ke kucing yang lain mel...,Pemberian antibiotic untuk mencegah adanya inf...,https://4.bp.blogspot.com/-xd0e9_RbMUg/V0u6PaH...
4,P5,Dermatophytosis,Iklim yang lembab dan hangat;Buruk sanitasi ka...,kucing liar yang tidak terkontrol karena dibe...,https://kucinggaul.com/wp-content/uploads/2014...

In [9]:
with open('model.pkl', 'rb') as m:
    model2 = pickle.load(m)

In [10]:
predicted= model2.predict([[1,1,0,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1]])
predicted_labels = predicted.tolist()
for label in predicted_labels:
    label_name = labels.loc[labels['DiseaseId'] == label]['DiseaseName'][0]
    print(label_name)

Scabies

In [11]:
from sklearn.metrics import confusion_matrix
y_prediction = model.predict(x)
cm = confusion_matrix(y, y_prediction)
cm

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)